// BL-9 round 5 (task A3) — a hand-composed list of common English words,
// used ONLY to widen scripts/search/build-static-embeddings.mjs's pruned
// vocabulary beyond the exact words that already appear in
// content/products.ts, so a query using generic phrasing still has
// in-vocabulary words to embed.
//
// Deliberately does NOT include any word drawn from
// evals/project-search/fixtures/*.json's queries — pulling eval-query
// vocabulary into the build-time vocabulary would inflate this tier's
// measured recall relative to how it would perform on real, unseen visitor
// queries (the eval set would no longer be held out). This list is generic
// English/tech/product vocabulary composed independently of the eval set;
// any overlap with an eval query's words is incidental (common words like
// "detect" or "review" are common precisely because they're common, not
// because they were copied from a fixture).
//
// Not sourced from a frequency corpus — hand-composed for coverage across
// general English plus software/product/business domains a recruiter
// browsing an AI/ML portfolio might plausibly type. Deduplicated and
// counted at build time (see build-static-embeddings.mjs); the exact count
// is reported there, never estimated here.
export const COMMON_VOCAB_WORDS = [
  // common function-adjacent words, verbs, everyday vocabulary
  "time", "help", "make", "build", "built", "find", "show", "need", "want",
  "learn", "understand", "message", "data", "information", "number", "price",
  "cost", "free", "easy", "fast", "slow", "small", "large", "quality", "safe",
  "secure", "private", "public", "personal", "real", "fake", "true", "false",
  "similar", "different", "same", "new", "old", "modern", "simple", "complex",
  "automatic", "manual", "smart", "intelligent", "artificial", "digital",
  "online", "mobile", "web", "cloud", "server", "database", "code",
  "software", "hardware", "system", "network", "security", "privacy",
  "algorithm", "machine", "learning", "deep", "neural", "language", "natural",
  "processing", "vision", "image", "video", "audio", "text", "voice",
  "speech", "translate", "translation", "summarize", "summary", "classify",
  "classification", "predict", "prediction", "forecast", "recommend",
  "recommendation", "search", "discover", "explore", "browse", "filter",
  "sort", "rank", "score", "rate", "review", "feedback", "comment", "chat",
  "conversation", "assistant", "agent", "bot", "tool", "app", "application",
  "platform", "service", "product", "project", "portfolio", "resume", "job",
  "work", "career", "hire", "hiring", "recruit", "recruiter", "company",
  "business", "startup", "market", "customer", "user", "client", "team",
  "developer", "engineer", "designer", "manager", "analyst", "scientist",
  "researcher", "student", "teacher", "doctor", "patient", "hospital",
  "health", "medical", "finance", "financial", "bank", "banking", "money",
  "budget", "expense", "spending", "saving", "investment", "stock",
  "trading", "insurance", "tax", "accounting", "legal", "law", "government",
  "policy", "education", "school", "university", "course", "training",
  "skill", "experience", "knowledge", "expert", "professional", "industry",
  "sector", "technology", "innovation", "solution", "problem", "issue",
  "bug", "error", "fix", "repair", "maintain", "maintenance", "update",
  "upgrade", "install", "setup", "configure", "deploy", "launch", "release",
  "version", "feature", "function", "performance", "speed", "efficiency",
  "efficient", "reliability", "scalability", "availability", "accessible",
  "accessibility", "usability", "design", "interface", "workflow", "process",
  "pipeline", "automation", "integration", "migration", "backup", "recovery",
  "monitoring", "logging", "testing", "debugging", "optimization",
  "compression", "encryption", "decryption", "authentication",
  "authorization", "validation", "verification", "detect", "detection",
  "recognize", "recognition", "generate", "generation", "creation",
  "production", "manufacturing", "retail", "ecommerce", "shopping", "store",
  "inventory", "supply", "chain", "logistics", "shipping", "delivery",
  "order", "purchase", "payment", "transaction", "subscription",
  "membership", "loyalty", "reward", "discount", "coupon", "sale", "offer",
  "deal", "demand", "trend", "pattern", "analysis", "insight", "report",
  "dashboard", "metric", "statistic", "measurement", "evaluation",
  "benchmark", "comparison", "ranking", "rating", "grade", "survey", "poll",
  "vote", "opinion", "sentiment", "emotion", "mood", "tone", "style",
  "fashion", "clothing", "apparel", "outfit", "wardrobe", "accessory",
  "jewelry", "beauty", "cosmetic", "skincare", "makeup", "hair", "art",
  "painting", "drawing", "illustration", "photography", "photo", "picture",
  "graphic", "animation", "film", "movie", "music", "song", "sound", "game",
  "gaming", "entertainment", "media", "social", "community", "forum",
  "blog", "article", "news", "publication", "content", "creator",
  "influencer", "brand", "marketing", "advertising", "campaign",
  "promotion", "strategy", "planning", "execution", "management",
  "leadership", "organization", "structure", "culture", "value", "mission",
  "vision", "goal", "objective", "target", "milestone", "deadline",
  "schedule", "calendar", "event", "meeting", "conference", "presentation",
  "document", "file", "folder", "storage", "sync", "share", "collaborate",
  "communicate", "connect", "link", "integrate", "combine", "merge",
  "split", "separate", "divide", "group", "categorize", "organize",
  "arrange", "priority", "urgent", "important", "critical", "essential",
  "optional", "required", "mandatory", "voluntary", "flexible", "rigid",
  "dynamic", "static", "adaptive", "responsive", "interactive", "custom",
  "personalized", "tailored", "generic", "standard", "default", "advanced",
  "basic", "beginner", "expert", "intermediate", "level", "tier", "layer",
  "module", "component", "element", "part", "piece", "unit", "item",
  "object", "entity", "instance", "class", "category", "type", "kind",
  "form", "shape", "size", "dimension", "scale", "range", "scope",
  "boundary", "limit", "constraint", "restriction", "permission", "access",
  "control", "risk", "threat", "vulnerability", "exploit", "attack",
  "defense", "protection", "prevention", "response", "resilience",
  "robustness", "stability", "consistency", "accuracy", "precision",
  "correctness", "validity", "integrity", "completeness", "coverage",
  "thoroughness", "depth", "breadth", "extent", "degree", "amount",
  "quantity", "volume", "capacity", "throughput", "latency", "delay",
  "wait", "duration", "period", "interval", "frequency", "ratio",
  "proportion", "percentage", "fraction", "portion", "total", "sum",
  "average", "distribution", "correlation", "relationship", "connection",
  "association", "dependency", "requirement", "prerequisite", "condition",
  "criterion", "threshold", "cluster", "vector", "embedding", "token",
  "tokenizer", "model", "training", "inference", "dataset", "sample",
  "label", "annotation", "supervised", "unsupervised", "reinforcement",
  "transformer", "attention", "layer", "weight", "parameter", "gradient",
  "loss", "accuracy", "regression", "classification", "clustering",
  "anomaly", "outlier", "noise", "signal", "trigger", "alert", "notify",
  "notification", "reminder", "task", "todo", "checklist", "template",
  "framework", "library", "package", "dependency", "repository", "branch",
  "commit", "merge", "pull", "push", "clone", "fork", "issue", "ticket",
  "triage", "on-call", "incident", "outage", "downtime", "uptime",
  "reliable", "fraud", "spam", "scam", "phishing", "malware", "virus",
  "backdoor", "breach", "leak", "exposure", "compliance", "regulation",
  "audit", "governance", "transparency", "explainability", "interpret",
  "interpretable", "bias", "fairness", "ethics", "responsible", "trust",
  "trustworthy", "verify", "verified", "authentic", "genuine", "legitimate",
  "counterfeit", "duplicate", "unique", "identical", "match", "mismatch",
  "compare", "contrast", "difference", "gap", "overlap", "intersection",
  "union", "subset", "superset", "sample", "population", "cohort", "segment",
  "audience", "demographic", "persona", "profile", "identity", "credential",
  "token", "session", "cache", "queue", "buffer", "stream", "batch",
  "realtime", "offline", "sync", "async", "concurrent", "parallel",
  "sequential", "serial", "distributed", "centralized", "decentralized",
  "microservice", "monolith", "container", "orchestration", "deployment",
  "environment", "infrastructure", "architecture", "topology", "endpoint",
  "route", "gateway", "proxy", "firewall", "load", "balance", "balancer",
  "traffic", "bandwidth", "throughput", "capacity", "resource", "instance",
  "cluster", "node", "shard", "partition", "replica", "backup", "snapshot",
  "restore", "rollback", "revert", "history", "log", "trace", "span",
  "metric", "dimension", "tag", "label", "annotation", "comment", "note",
  "reminder", "checklist", "template", "boilerplate", "scaffold",
  "generator", "wizard", "onboarding", "tutorial", "guide", "documentation",
  "reference", "manual", "handbook", "cheatsheet", "faq", "support",
  "helpdesk", "ticketing", "escalation", "resolution", "root", "cause",
  "diagnosis", "symptom", "remedy", "workaround", "patch", "hotfix",
  "regression", "flaky", "stable", "unstable", "deprecated", "legacy",
  "modernize", "refactor", "rewrite", "port", "migrate", "convert",
  "transform", "extract", "load", "clean", "cleanse", "normalize",
  "denormalize", "aggregate", "summarize", "compress", "decompress",
  "encode", "decode", "serialize", "deserialize", "parse", "format",
  "render", "display", "preview", "print", "export", "import", "upload",
  "download", "attach", "attachment", "embed", "widget", "plugin",
  "extension", "addon", "integration", "webhook", "callback", "trigger",
  "hook", "listener", "observer", "publisher", "subscriber", "topic",
  "channel", "broadcast", "multicast", "unicast", "peer", "host", "client",
  "server", "backend", "frontend", "fullstack", "api", "rest", "graphql",
  "grpc", "websocket", "protocol", "schema", "contract", "specification",
  "standard", "compliance", "certification", "license", "open", "closed",
  "source", "proprietary", "commercial", "enterprise", "consumer",
  "b2b", "b2c", "saas", "paas", "iaas", "cloud", "hybrid", "onprem",
  "premises", "datacenter", "region", "zone", "availability", "redundancy",
  "failover", "disaster", "recovery", "continuity", "sla", "slo", "sli",
];
